# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '8_bit.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(515, 503)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_data = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_data.setGeometry(QtCore.QRect(20, 130, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineEdit_data.setFont(font)
        self.lineEdit_data.setText("")
        self.lineEdit_data.setObjectName("lineEdit_data")
        self.lineEdit_check_bit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_check_bit.setGeometry(QtCore.QRect(380, 130, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineEdit_check_bit.setFont(font)
        self.lineEdit_check_bit.setText("")
        self.lineEdit_check_bit.setObjectName("lineEdit_check_bit")
        self.lineEdit_memory = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_memory.setGeometry(QtCore.QRect(150, 250, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lineEdit_memory.setFont(font)
        self.lineEdit_memory.setText("")
        self.lineEdit_memory.setObjectName("lineEdit_memory")
        self.pushButton_memory = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_memory.setGeometry(QtCore.QRect(30, 250, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_memory.setFont(font)
        self.pushButton_memory.setObjectName("pushButton_memory")
        self.pushButton_control = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_control.setGeometry(QtCore.QRect(370, 250, 81, 31))
        self.pushButton_control.setObjectName("pushButton_control")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 330, 471, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 110, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_check_bits = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_check_bits.setGeometry(QtCore.QRect(240, 140, 91, 31))
        self.pushButton_check_bits.setObjectName("pushButton_check_bits")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_memory.setText(_translate("MainWindow", "Bring Memory"))
        self.pushButton_control.setText(_translate("MainWindow", "Control"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Hamming Code Simulator for 8 Bit Data\'s"))
        self.label_2.setText(_translate("MainWindow", "Data"))
        self.label_3.setText(_translate("MainWindow", "Check Bits"))
        self.pushButton_check_bits.setText(_translate("MainWindow", "Find Check Bits"))