# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(637, 538)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_baslik = QtWidgets.QLabel(self.centralwidget)
        self.label_baslik.setGeometry(QtCore.QRect(140, 20, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_baslik.setFont(font)
        self.label_baslik.setObjectName("label_baslik")
        self.pushButton_8bit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8bit.setGeometry(QtCore.QRect(230, 170, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_8bit.setFont(font)
        self.pushButton_8bit.setObjectName("pushButton_8bit")
        self.pushButton_16bit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16bit.setGeometry(QtCore.QRect(230, 250, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_16bit.setFont(font)
        self.pushButton_16bit.setObjectName("pushButton_16bit")
        self.pushButton_32bit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_32bit.setGeometry(QtCore.QRect(230, 330, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_32bit.setFont(font)
        self.pushButton_32bit.setObjectName("pushButton_32bit")
        self.label_aciklama = QtWidgets.QLabel(self.centralwidget)
        self.label_aciklama.setGeometry(QtCore.QRect(160, 100, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_aciklama.setFont(font)
        self.label_aciklama.setObjectName("label_aciklama")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_baslik.setText(_translate("MainWindow", "Hamming SEC-DED Code Simulator"))
        self.pushButton_8bit.setText(_translate("MainWindow", "8 BIT"))
        self.pushButton_16bit.setText(_translate("MainWindow", "16 BIT"))
        self.pushButton_32bit.setText(_translate("MainWindow", "32 BIT"))
        self.label_aciklama.setText(_translate("MainWindow", "İşlem yapmak istediğiniz bit sayısını seçiniz"))

